export type C2ConnectionMode = 'SETUP_MODE' | 'OPS_MONITOR_MODE' | 'PRAMAAN_CONTROL_MODE' | 'FUTURE_SECURE_CONTROL_MODE';
export type MAVLinkBridgeStatus = 'NOT_CONFIGURED' | 'SIMULATION_ONLY' | 'READ_ONLY_READY' | 'CONNECTED_READ_ONLY' | 'ERROR';
export type MissionDraftStatus = 'DRAFT' | 'VALIDATED' | 'INVALID' | 'LOCKED';
export type WaypointAction = 'NAVIGATE' | 'LOITER' | 'CAPTURE_IMAGE' | 'START_RECORDING' | 'STOP_RECORDING' | 'RETURN_POINT';

export interface BridgeStatus { status: MAVLinkBridgeStatus; read_only: boolean; endpoint_count: number; message: string; hardware_commands_enabled: boolean; }
export interface MAVLinkEndpoint { id: number; endpoint_id: string; name: string; host: string; port: number; protocol: string; status: MAVLinkBridgeStatus; read_only: boolean; created_at: string; updated_at: string; }
export interface C2ConnectionConfig { id?: number; mode: C2ConnectionMode; description: string; mission_planner_allowed: boolean; pramaan_commands_allowed: boolean; hardware_commands_enabled: boolean; puf_required: boolean; created_at?: string; updated_at?: string; }

export interface MissionDraft { id: number; mission_id: string; name: string; drone_id: string; vehicle_type: 'QUADCOPTER' | 'FIXED_WING'; status: MissionDraftStatus; default_altitude_m: number; default_speed_mps: number; lost_link_action: string; created_at: string; updated_at: string; }
export interface MissionDraftCreate { name: string; drone_id: string; vehicle_type: 'QUADCOPTER' | 'FIXED_WING'; default_altitude_m: number; default_speed_mps: number; lost_link_action: string; }
export interface MapWaypoint { id: number; mission_id: string; sequence: number; lat: number; lon: number; altitude_m: number; speed_mps: number; action: WaypointAction; loiter_seconds?: number | null; notes?: string | null; }
export interface MapWaypointCreate { lat: number; lon: number; altitude_m?: number; speed_mps?: number; action: WaypointAction; loiter_seconds?: number | null; notes?: string | null; }
export interface MissionRouteSummary { waypoint_count: number; estimated_distance_m: number; max_altitude_m: number; min_altitude_m: number; }
export interface MissionValidation { mission_id: string; status: MissionDraftStatus; valid: boolean; warnings: string[]; errors: string[]; summary: MissionRouteSummary; }
export interface GeofenceDraft { id: number; geofence_id: string; name: string; drone_id: string; enabled: boolean; polygon_json: string; max_altitude_m: number; min_altitude_m: number; created_at: string; updated_at: string; }
export type TelemetrySource = 'MOCK' | 'MAVLINK_READ_ONLY' | 'PLAYBACK';
export type TelemetrySourceStatus = 'ACTIVE' | 'INACTIVE' | 'CONNECTING' | 'ERROR';
export interface TelemetrySourceConfig { id: number; source_type: TelemetrySource; active_source?: TelemetrySource; status: TelemetrySourceStatus; name: string; host?: string | null; port?: number | null; protocol: string; read_only: boolean; last_error?: string | null; created_at: string; updated_at: string; message?: string; }
export interface MissionEvent { id: number; mission_id: string; drone_id: string; event_type: string; severity: string; message: string; timestamp: string; details?: string | null; }
export interface MissionSimulationStatus { mission_id: string; state: 'IDLE' | 'RUNNING' | 'PAUSED' | 'COMPLETED' | 'ERROR'; active_waypoint_index: number; waypoint_count: number; message: string; }

export interface MAVLinkReadonlyStatus { connected: boolean; read_only: boolean; commands_enabled: boolean; command_sending_enabled?: boolean; mission_upload_enabled?: boolean; parameter_write_enabled?: boolean; mode_change_enabled?: boolean; arming_enabled?: boolean; takeoff_enabled?: boolean; hardware_control_enabled?: boolean; host: string; port: number; protocol: string; endpoint: string; last_error?: string | null; last_message_time?: string | null; message_counts: Record<string, number>; received_since_connect: boolean; supported_protocols: Record<string, string>; ok?: boolean; }
export interface BenchReadiness { stage: string; bench_mode: boolean; propellers_required_removed: boolean; read_only: boolean; hardware_commands_enabled: boolean; serial_supported: string; recommended_connection: string; checklist: string[]; warnings: string[]; }
export interface ConnectionProfile { id: number; profile_id: string; name: string; profile_type: 'SITL_UDP' | 'MAVPROXY_UDP' | 'PIXHAWK_SERIAL_PLACEHOLDER' | 'PLAYBACK'; host?: string | null; port?: number | null; serial_port?: string | null; baud_rate?: number | null; protocol: string; read_only: boolean; enabled: boolean; notes?: string | null; created_at: string; updated_at: string; }
export interface SITLReadiness { status: string; read_only: boolean; command_sending_enabled: boolean; expected_host: string; expected_port: number; telemetry_source: string; mavlink_provider_status: string; mission_planner_role: string; pramaanx_role: string; checklist: string[]; warnings: string[]; recommended_next_step: string; sitl_supported: boolean; mavlink_readonly_supported: boolean; recommended_sitl_out: string; mission_planner_coexistence: boolean; documentation_only_commands: string[]; }
export interface SystemStatus { app_name: string; company: string; app_stage: string; simulation_only: boolean; hardware_commands_enabled: boolean; mavlink_command_sending_enabled: boolean; pufshield_integrated: boolean; active_telemetry_source: string; backend_status: string; warning_count: number; }
export interface TelemetryIntelligence { drone_id: string; battery_level: number; battery_risk: string; altitude_status: string; speed_status: string; gps_status: string; telemetry_freshness: string; recommended_action: string; warnings: string[]; summary: string; timestamp: string; }
export interface LinkIntelligence { drone_id: string; link_state: string; link_quality: string; operator_message: string; risk_level: string; recommended_action: string; timestamp: string; }
export interface IntelligenceSummary { drone_id: string; telemetry: TelemetryIntelligence; link: LinkIntelligence; warnings: string[]; simulation_only: boolean; hardware_commands_enabled: boolean; }
export interface MissionExport { format: string; mission: MissionDraft; waypoints: MapWaypoint[]; validation: MissionValidation; exported_at: string; hardware_upload_enabled: boolean; }
export interface MissionImportPayload { format: string; mission: MissionDraftCreate & { mission_id?: string }; waypoints: MapWaypointCreate[]; }
export interface MissionReport { mission_id: string; name: string; drone_id: string; vehicle_type: string; status: string; waypoint_count: number; estimated_distance_m: number; estimated_duration_s: number; max_altitude_m: number; min_altitude_m: number; lost_link_action: string; validation_errors: string[]; validation_warnings: string[]; simulation_only: boolean; hardware_upload_enabled: boolean; }
