from enum import StrEnum


class VehicleType(StrEnum):
    QUADCOPTER = "QUADCOPTER"
    FIXED_WING = "FIXED_WING"


class DroneState(StrEnum):
    UNSEEN = "UNSEEN"
    CONNECTED = "CONNECTED"
    READY = "READY"
    DEGRADED = "DEGRADED"
    LOST_LINK = "LOST_LINK"
    ERROR = "ERROR"


class MissionState(StrEnum):
    IDLE = "IDLE"
    PLANNED = "PLANNED"
    VALIDATED = "VALIDATED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"


class LinkState(StrEnum):
    FULL_LINK = "FULL_LINK"
    DEGRADED_LINK = "DEGRADED_LINK"
    INTERMITTENT_LINK = "INTERMITTENT_LINK"
    LOST_LINK = "LOST_LINK"
    RECOVERED_LINK = "RECOVERED_LINK"


class CommandType(StrEnum):
    READ_STATUS = "READ_STATUS"
    START_LOGGING = "START_LOGGING"
    STOP_LOGGING = "STOP_LOGGING"
    SIMULATE_RTL = "SIMULATE_RTL"
    SIMULATE_LAND = "SIMULATE_LAND"


class CommandStatus(StrEnum):
    QUEUED = "QUEUED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    REJECTED = "REJECTED"


class GovernanceDecision(StrEnum):
    ALLOW = "ALLOW"
    REJECT = "REJECT"
    WARN_REQUIRE_CONFIRMATION = "WARN_REQUIRE_CONFIRMATION"


class C2ConnectionMode(StrEnum):
    SETUP_MODE = "SETUP_MODE"
    OPS_MONITOR_MODE = "OPS_MONITOR_MODE"
    PRAMAAN_CONTROL_MODE = "PRAMAAN_CONTROL_MODE"
    FUTURE_SECURE_CONTROL_MODE = "FUTURE_SECURE_CONTROL_MODE"


class MAVLinkBridgeStatus(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    SIMULATION_ONLY = "SIMULATION_ONLY"
    READ_ONLY_READY = "READ_ONLY_READY"
    CONNECTED_READ_ONLY = "CONNECTED_READ_ONLY"
    ERROR = "ERROR"


class MissionDraftStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    INVALID = "INVALID"
    LOCKED = "LOCKED"


class WaypointAction(StrEnum):
    NAVIGATE = "NAVIGATE"
    LOITER = "LOITER"
    CAPTURE_IMAGE = "CAPTURE_IMAGE"
    START_RECORDING = "START_RECORDING"
    STOP_RECORDING = "STOP_RECORDING"
    RETURN_POINT = "RETURN_POINT"



class TelemetrySource(StrEnum):
    MOCK = "MOCK"
    MAVLINK_READ_ONLY = "MAVLINK_READ_ONLY"
    PLAYBACK = "PLAYBACK"


class TelemetrySourceStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    CONNECTING = "CONNECTING"
    ERROR = "ERROR"


class MissionSimulationState(StrEnum):
    IDLE = "IDLE"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"


class MissionEventType(StrEnum):
    MISSION_SIM_STARTED = "MISSION_SIM_STARTED"
    MISSION_SIM_STOPPED = "MISSION_SIM_STOPPED"
    WAYPOINT_REACHED = "WAYPOINT_REACHED"
    MISSION_VALIDATED = "MISSION_VALIDATED"
    MISSION_INVALID = "MISSION_INVALID"
    SOURCE_SWITCHED = "SOURCE_SWITCHED"
    MAVLINK_READONLY_ERROR = "MAVLINK_READONLY_ERROR"
